version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: virtua_lms_db
    environment:
      POSTGRES_USER: virtua_user
      POSTGRES_PASSWORD: virtua_password
      POSTGRES_DB: virtua_lms
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: virtua_lms_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
