// Isolated visual QA entry, excluded from the production build. All requests
// terminate in this in-memory fixture; it never authenticates or calls an API.
import { createRoot } from 'react-dom/client';
import ConsoleApp from '../src/console/ConsoleApp';
import { AuthContext } from '../src/auth/context';
import '../src/index.css';

const role = new URLSearchParams(location.search).get('role') || 'SUPER_ADMIN';
const person = { id: 'author-1', firstName: 'Aarav', lastName: 'Shah', email: 'aarav@example.test' };
const records = ['Design thinking: from insight to impact', 'The foundations of modern web development', 'Brand strategy for ambitious businesses', 'A practical guide to visual storytelling', 'Design systems that scale', 'Building your first digital product'].map((title, i) => ({ id: `course-${i + 1}`, title, shortDescription: 'Learn the principles, practice the process, and build the confidence to create meaningful work.', description: 'A practical, project-based introduction. You’ll learn to identify the right problems, explore ideas, and create thoughtful solutions.', status: ['DRAFT','IN_REVIEW','ON_AIR','CHANGES_REQUESTED','APPROVED','DRAFT'][i], updatedAt: '2026-09-28T10:00:00Z', course: { id: `content-${i}`, authorId: person.id, author: person, category: { name: ['DESIGN & CREATIVITY','DEVELOPMENT','BUSINESS'][i % 3] }, level: 'BEGINNER', language: 'en', _count: { sections: 2 }, sections: [{ id: `section-${i}`, title: 'Start with the right questions', description: 'Understand the foundations', position: 0, sessions: [{ id: `lesson-${i}`, title: 'Welcome to the course', description: 'An introduction to what we’ll learn together.', position: 0, status: 'VIDEO', isPreview: true, isFree: false, video: { vimeoVideoId: '123456789', duration: 420, status: 'READY' }, resources: [], questionnaire: null }, { id: `text-${i}`, title: 'Understanding your audience', description: 'Start by listening. Make a list of assumptions, then plan how you’ll test them.', position: 1, status: 'TEXT', isPreview: false, isFree: false, resources: [], questionnaire: null }] }, { id: `next-${i}`, title: 'From research to insight', description: '', position: 1, sessions: [] }] } }));
const applications = Array.from({ length: 12 }, (_, i) => ({ id: `application-${i}`, headline: 'Product designer & educator', bio: 'I help people build thoughtful digital products through research, practical projects, and clear feedback.', expertise: ['Product design','User research'], status: 'PENDING', user: { ...person, email: `instructor${i + 1}@example.test`, firstName: `Instructor ${i + 1}` }, createdAt: '2026-09-25T00:00:00Z' }));
const profile = { ...person, username: 'aarav', bio: 'Designer, educator, and lifelong learner.', roles: [role], isActive: true, createdAt: '', updatedAt: '' };
window.fetch = async (input, init) => {
  const url = new URL(String(input), location.origin); const path = url.pathname; const page = Number(url.searchParams.get('page') || 1); const limit = Number(url.searchParams.get('limit') || 10);
  const response = (data: unknown, status = 200) => Promise.resolve(new Response(JSON.stringify(data), { status, headers: { 'Content-Type': 'application/json' } }));
  if (new URLSearchParams(location.search).has('error')) return response({ message: 'The service is temporarily unavailable. Please try again.' }, 503);
  const empty = new URLSearchParams(location.search).has('empty');
  if (path === '/api/admin/users') return response({ items: empty ? [] : [profile], total: empty ? 0 : 1, page, totalPages: 1 });
  if (path.startsWith('/api/admin/users/') && init?.method === 'PATCH') return response(profile);
  if (path === '/api/users/profile') return response(init?.method === 'PUT' ? Object.assign(profile, JSON.parse(String(init.body))) : profile);
  if (path === '/api/admin/author-applications') { const list = empty ? [] : applications.filter(a => !url.searchParams.get('status') || a.status === url.searchParams.get('status')); return response({ items: list.slice((page - 1) * limit, page * limit), total: list.length, totalPages: Math.ceil(list.length / limit), page }); }
  if (path.includes('/admin/author-applications/') && init?.method === 'PATCH') { const a = applications.find(a => path.includes(a.id)); return response(Object.assign(a!, JSON.parse(String(init.body)))); }
  if (path === '/courses/manage') { const list = empty ? [] : records.filter(c => (!url.searchParams.get('status') || c.status === url.searchParams.get('status')) && c.title.toLowerCase().includes((url.searchParams.get('search') || '').toLowerCase())); return response({ courses: list.slice((page - 1) * limit, page * limit), total: list.length, totalPages: Math.ceil(list.length / limit), page }); }
  if (path.startsWith('/courses/manage/')) return response(records.find(c => c.id === path.split('/').pop()));
  if (path === '/categories/query') return response({ categories: [{ id: 'category-1', name: 'Design & creativity' }], totalPages: 1 });
  if (path === '/course-publishing/review-queue') return response({ submissions: [{ id: 'review-1', status: 'PENDING', submittedAt: '2026-09-27T10:00:00Z', submittedBy: person, product: records[1] }], total: 1, totalPages: 1 });
  if (path.endsWith('/submissions')) return response([{ id: 'submission-1', status: 'CHANGES_REQUESTED', reviewComment: 'Please add a practical exercise to the second section.', submittedAt: '2026-09-26T10:00:00Z', reviewedBy: person }]);
  if (path.includes('/publishing/') && init?.method === 'POST') { const course = records.find(c => c.id === path.split('/')[2]); const states: Record<string, string> = { submit: 'IN_REVIEW', approve: 'APPROVED', 'request-changes': 'CHANGES_REQUESTED', publish: 'ON_AIR', unpublish: 'DRAFT', archive: 'ARCHIVED' }; if (course) course.status = states[path.split('/').pop()!]; return response(course); }
  if (path === '/sections' && init?.method === 'POST') { const body = JSON.parse(String(init.body)); const course = records.find(c => c.id === body.courseId)!; const section = { id: `section-${Date.now()}`, title: body.title, description: body.description, position: course.course.sections.length, sessions: [] }; course.course.sections.push(section); return response(section); }
  return response({ message: 'This action is outside the visual fixture. Use the real API for integration verification.' }, 400);
};
createRoot(document.getElementById('root')!).render(<AuthContext.Provider value={{ initialized: true, authenticated: true, user: { id: person.id, name: 'Aarav Shah', email: person.email, username: 'aarav', roles: [role] }, token: undefined, error: null, refreshUser: async () => {}, login: () => {}, logout: () => {}, apiFetch: window.fetch }}><ConsoleApp /></AuthContext.Provider>);
